-- MULTILINGUAL 시드: 지도(map) 화면 정적 텍스트 (핵심 14키만)
-- 생성: chamApp/src/screens/MapScreen.tsx 의 상시 노출 정적 라벨 기준
-- 언어: KO/EN/ZH/JA/VI, MENU='map', MULTILINGUAL_ID는 auto-increment라 생략
-- NAME=텍스트 키(언어 공통), CONT=번역문
SET NAMES utf8mb4;

-- 대피소 유형 필터
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'filterAll', 'KO', '전체', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'filterAll', 'EN', 'All', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'filterAll', 'ZH', '全部', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'filterAll', 'JA', 'すべて', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'filterAll', 'VI', 'Tất cả', NOW(), NOW());

INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'civilDefenseShelter', 'KO', '민방위대피시설', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'civilDefenseShelter', 'EN', 'Civil Defense Shelter', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'civilDefenseShelter', 'ZH', '民防卫避难设施', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'civilDefenseShelter', 'JA', '民間防衛避難施設', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'civilDefenseShelter', 'VI', 'Cơ sở trú ẩn phòng vệ dân sự', NOW(), NOW());

INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'earthquakeShelter', 'KO', '지진대피장소', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'earthquakeShelter', 'EN', 'Earthquake Shelter', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'earthquakeShelter', 'ZH', '地震避难场所', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'earthquakeShelter', 'JA', '地震避難場所', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'earthquakeShelter', 'VI', 'Địa điểm trú ẩn động đất', NOW(), NOW());

INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'chemicalAccidentShelter', 'KO', '화학사고대피장소', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'chemicalAccidentShelter', 'EN', 'Chemical Accident Shelter', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'chemicalAccidentShelter', 'ZH', '化学事故避难场所', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'chemicalAccidentShelter', 'JA', '化学事故避難場所', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'chemicalAccidentShelter', 'VI', 'Địa điểm trú ẩn sự cố hóa chất', NOW(), NOW());

INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'earthquakeTempHousing', 'KO', '지진겸용 임시주거시설', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'earthquakeTempHousing', 'EN', 'Earthquake Temporary Housing', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'earthquakeTempHousing', 'ZH', '兼用地震临时住所', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'earthquakeTempHousing', 'JA', '地震兼用臨時住居施設', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'earthquakeTempHousing', 'VI', 'Nhà ở tạm thời kiêm động đất', NOW(), NOW());

INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'disasterTempHousing', 'KO', '이재민 임시주거시설', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'disasterTempHousing', 'EN', 'Disaster Victim Temporary Housing', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'disasterTempHousing', 'ZH', '灾民临时住所', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'disasterTempHousing', 'JA', '被災者臨時住居施設', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'disasterTempHousing', 'VI', 'Nhà ở tạm thời cho nạn nhân thiên tai', NOW(), NOW());

-- 접근성 필터
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'accessibilityAll', 'KO', '접근성 전체', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'accessibilityAll', 'EN', 'All Accessibility', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'accessibilityAll', 'ZH', '无障碍全部', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'accessibilityAll', 'JA', 'バリアフリーすべて', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'accessibilityAll', 'VI', 'Toàn bộ tiếp cận', NOW(), NOW());

INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'ramp', 'KO', '경사로', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'ramp', 'EN', 'Ramp', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'ramp', 'ZH', '坡道', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'ramp', 'JA', 'スロープ', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'ramp', 'VI', 'Đường dốc', NOW(), NOW());

INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'elevator', 'KO', '엘리베이터', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'elevator', 'EN', 'Elevator', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'elevator', 'ZH', '电梯', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'elevator', 'JA', 'エレベーター', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'elevator', 'VI', 'Thang máy', NOW(), NOW());

INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'brailleBlock', 'KO', '점자블록', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'brailleBlock', 'EN', 'Braille Block', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'brailleBlock', 'ZH', '盲道块', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'brailleBlock', 'JA', '点字ブロック', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'brailleBlock', 'VI', 'Khối chữ nổi', NOW(), NOW());

INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'accessibleToilet', 'KO', '장애인 화장실', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'accessibleToilet', 'EN', 'Accessible Toilet', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'accessibleToilet', 'ZH', '无障碍卫生间', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'accessibleToilet', 'JA', '車椅子対応トイレ', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'accessibleToilet', 'VI', 'Nhà vệ sinh cho người khuyết tật', NOW(), NOW());

-- 하단 패널 상시 라벨
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'totalShelters', 'KO', '총 대피소', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'totalShelters', 'EN', 'Total shelters', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'totalShelters', 'ZH', '避难所总数', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'totalShelters', 'JA', '避難所の合計', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'totalShelters', 'VI', 'Tổng số nơi trú ẩn', NOW(), NOW());

INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'loadingShelters', 'KO', '대피소 정보를 불러오는 중', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'loadingShelters', 'EN', 'Loading shelter information', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'loadingShelters', 'ZH', '正在加载避难所信息', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'loadingShelters', 'JA', '避難所情報を読み込み中', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'loadingShelters', 'VI', 'Đang tải thông tin nơi trú ẩn', NOW(), NOW());

INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'nearbyButton', 'KO', '내 위치 주변 보기', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'nearbyButton', 'EN', 'View nearby', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'nearbyButton', 'ZH', '查看我附近', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'nearbyButton', 'JA', '現在地周辺を見る', NOW(), NOW());
INSERT INTO CHAM_EQUALITY.MULTILINGUAL (MENU, NAME, LANGUAGE, CONT, CREATE_DATE, MODIFY_DATE) VALUES ('map', 'nearbyButton', 'VI', 'Xem quanh vị trí của tôi', NOW(), NOW());
