spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_batch_fetch_size: 30
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://${DB_URL}:${DB_PORT}/CHAM_EQUALITY
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION}
      s3:
        bucket: ${AWS_BUCKET}

auth:
  cookie:
    name: refreshToken
    secure: ${COOKIE_SECURE:true}
    path: /
    same-site: Strict
  refresh-token:
    expiry: 1d


logging:
  file:
    name: /home/cham/cham-equality-log/cham.log
    level:
      root: INFO
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log
cors:
  url: https://cham-monimap.com

admin:
  password: ${ADMIN_PASSWORD}